#!/usr/bin/env bash
# nginx/setup-tls.sh
#
# One-shot TLS setup for the axi-react VM (10.0.2.146, office-network-only).
#
# What this does:
#   1. Generates a self-signed certificate valid for the VM's IP (SAN required
#      by all modern browsers -- a CN-only cert is rejected even if self-signed).
#   2. Writes /etc/nginx/conf.d/axi-tls.conf:
#        - Port 443 HTTPS server block with all existing proxy locations.
#        - Port 80 → 443 permanent redirect.
#   3. Tests and reloads nginx.
#
# Run once on the VM:
#   sudo bash nginx/setup-tls.sh
#
# After running, distribute /etc/nginx/ssl/axi.crt to each team member's
# device as a trusted root CA cert. Instructions at the bottom of this script.
#
# Re-running is safe: cert and config are regenerated from scratch.

set -euo pipefail

VM_IP="10.0.2.146"
SSL_DIR="/etc/nginx/ssl"
CERT="$SSL_DIR/axi.crt"
KEY="$SSL_DIR/axi.key"
CONF="/etc/nginx/conf.d/axi-tls.conf"
DAYS=825   # max accepted by iOS; ~2.25 years

# ── 1. Generate cert ──────────────────────────────────────────────────────────

echo "[1/3] Generating self-signed cert for IP $VM_IP..."
mkdir -p "$SSL_DIR"
chmod 700 "$SSL_DIR"

openssl req -x509 \
  -newkey rsa:4096 \
  -keyout "$KEY" \
  -out    "$CERT" \
  -days   "$DAYS" \
  -nodes \
  -subj   "/CN=$VM_IP/O=Axi Chat/OU=Dev" \
  -addext "subjectAltName=IP:$VM_IP"

chmod 600 "$KEY"
chmod 644 "$CERT"

echo "    Cert: $CERT"
echo "    Key:  $KEY"
echo "    Valid: $DAYS days"

# ── 2. Write nginx HTTPS config ───────────────────────────────────────────────

echo "[2/3] Writing $CONF..."

cat > "$CONF" << 'NGINX'
# /etc/nginx/conf.d/axi-tls.conf
# Generated by nginx/setup-tls.sh — do not edit by hand.
# Re-run setup-tls.sh to regenerate.

# ---- HTTP → HTTPS redirect ---------------------------------------------------
server {
    listen 80 default_server;
    return 301 https://$host$request_uri;
}

# ---- HTTPS production server -------------------------------------------------
server {
    listen 443 ssl default_server;
    server_name _;

    ssl_certificate     /etc/nginx/ssl/axi.crt;
    ssl_certificate_key /etc/nginx/ssl/axi.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # ── WebSocket (wss://) ────────────────────────────────────────────────────
    location /ws {
        proxy_pass http://127.0.0.1:8080/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host       $host;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # ── File upload ───────────────────────────────────────────────────────────
    location /upload {
        proxy_pass http://127.0.0.1:8080/upload;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
        client_max_body_size 9m;
    }

    # ── Uploaded files (served by backend, path-traversal-safe) ──────────────
    location /uploads/ {
        proxy_pass http://127.0.0.1:8080/uploads/;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── Sandesh REST API (/api/sd/* — setup, login, OTP, sessions, files) ─────
    # Longer prefix wins over the frontend catch-all below.
    location /api/sd/ {
        proxy_pass http://127.0.0.1:8080/api/sd/;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── React frontend (static build) ─────────────────────────────────────────
    location / {
        root  /var/www/axi-react;
        try_files $uri $uri/ /index.html;
    }
}

# ── map block required for WebSocket upgrade header (add once, globally) ──────
# Already present in most nginx installs; harmless if duplicated in a separate
# file. If nginx -t complains about a duplicate `map` block, remove this and
# put it in /etc/nginx/nginx.conf's http {} block instead.
NGINX

# ── 3. Test and reload ────────────────────────────────────────────────────────

echo "[3/3] Testing nginx config and reloading..."
nginx -t
systemctl reload nginx

echo ""
echo "Done. HTTPS is live at https://$VM_IP/"
echo ""
echo "══════════════════════════════════════════════════════════════════════"
echo "  NEXT STEP — install the cert as a trusted root on team devices"
echo "══════════════════════════════════════════════════════════════════════"
echo ""
echo "  The cert file to distribute:  $CERT"
echo "  (copy it off the VM with scp, airdrop, USB, whatever is handy)"
echo ""
echo "  Android (one-time per device):"
echo "    Settings → Security → Encryption & credentials"
echo "    → Install a certificate → CA certificate → pick axi.crt"
echo "    The certificate name will show as 'Axi Chat'."
echo ""
echo "  iOS / iPadOS (one-time per device):"
echo "    1. AirDrop or email axi.crt to the device → tap to open → 'Profile Downloaded'"
echo "    2. Settings → General → VPN & Device Management → install the profile"
echo "    3. Settings → General → About → Certificate Trust Settings"
echo "       → enable 'Axi Chat' under 'Enable Full Trust For Root Certificates'"
echo "       (iOS requires this extra step for self-signed CAs — Apple's UX, not ours)"
echo ""
echo "  macOS:"
echo "    sudo security add-trusted-cert -d -r trustRoot \\"
echo "      -k /Library/Keychains/System.keychain $CERT"
echo ""
echo "  Windows:"
echo "    certlm.msc → Trusted Root Certification Authorities → Certificates"
echo "    → right-click → All Tasks → Import → pick axi.crt"
echo ""
echo "  After installing the cert, https://$VM_IP/ works like any trusted site"
echo "  and getUserMedia (camera) is unblocked in the browser."
echo "══════════════════════════════════════════════════════════════════════"
